//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcm.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsk_tasks_history
    {
        public int history_id { get; set; }
        public System.Guid task_id { get; set; }
        public System.Guid related_project_id { get; set; }
        public System.Guid assigned_user_id { get; set; }
        public Nullable<int> task_type_id { get; set; }
        public int task_status_id { get; set; }
        public int task_priority_id { get; set; }
        public string task_name { get; set; }
        public string task_description { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<System.Guid> history_by { get; set; }
        public Nullable<System.DateTime> history_at { get; set; }
    }
}
