//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcm.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_projects
    {
        public System.Guid project_id { get; set; }
        public System.Guid kurum_id { get; set; }
        public System.Guid birey_id { get; set; }
        public int project_type_id { get; set; }
        public Nullable<System.Guid> project_assigned_user_id { get; set; }
        public string project_name { get; set; }
        public string project_description { get; set; }
        public string note { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.Guid> inserted_by { get; set; }
        public Nullable<System.DateTime> inserted_at { get; set; }
        public Nullable<System.Guid> updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.Guid> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<System.Guid> statik { get; set; }
        public Nullable<System.Guid> elektrik { get; set; }
        public Nullable<System.Guid> mekanik { get; set; }
        public Nullable<System.Guid> harita { get; set; }
        public Nullable<System.Guid> yapı_denetimi { get; set; }
        public string isveren_mobile_phone { get; set; }
        public Nullable<decimal> metre_kare { get; set; }
    }
}
