//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcm.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_bireyler_kurumlar_v
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
