//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcm.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class gnl_logged_in_users
    {
        public int id { get; set; }
        public string type { get; set; }
        public Nullable<System.Guid> user_uid { get; set; }
        public string user_name { get; set; }
        public string user_name_surname { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string session_id { get; set; }
        public string host_name { get; set; }
        public string user_host_adres { get; set; }
        public string browser { get; set; }
        public string platform { get; set; }
        public string version { get; set; }
    }
}
