//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcm.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class gnl_user_groups
    {
        public System.Guid group_id { get; set; }
        public string group_name { get; set; }
        public string group_explanation { get; set; }
        public Nullable<System.Guid> manager_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.Guid> inserted_by { get; set; }
        public Nullable<System.DateTime> inserted_at { get; set; }
        public Nullable<System.Guid> updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.Guid> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
