//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcm.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskEntities : DbContext
    {
        public TaskEntities()
            : base("name=TaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ref_tsk_task_priority> ref_tsk_task_priority { get; set; }
        public virtual DbSet<ref_tsk_task_status> ref_tsk_task_status { get; set; }
        public virtual DbSet<tsk_tasks_history> tsk_tasks_history { get; set; }
        public virtual DbSet<tsk_task_history_v> tsk_task_history_v { get; set; }
        public virtual DbSet<tsk_tasks> tsk_tasks { get; set; }
        public virtual DbSet<tsk_tasks_v> tsk_tasks_v { get; set; }
    }
}
