//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcm.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_bireyler
    {
        public System.Guid birey_id { get; set; }
        public System.Guid calistigi_kurum_id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public Nullable<int> turu_id { get; set; }
        public string eposta_adresi { get; set; }
        public string mobile_phone { get; set; }
        public string telefonu_1 { get; set; }
        public string telefonu_2 { get; set; }
        public string faksi_1 { get; set; }
        public string faksi_2 { get; set; }
        public string adres { get; set; }
        public string web_sitesi { get; set; }
        public string note { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.Guid> inserted_by { get; set; }
        public Nullable<System.DateTime> inserted_at { get; set; }
        public Nullable<System.Guid> updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.Guid> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
