//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcm.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsk_tasks_v
    {
        public System.Guid task_id { get; set; }
        public string task_name { get; set; }
        public string task_priority_name { get; set; }
        public string task_status_name { get; set; }
        public string project_name { get; set; }
        public string assigned_user_name { get; set; }
        public string task_owner { get; set; }
        public string start_date { get; set; }
        public System.DateTime start_date1 { get; set; }
        public System.DateTime end_date1 { get; set; }
        public string end_date { get; set; }
        public string is_active { get; set; }
        public System.Guid task_user_id { get; set; }
        public System.Guid assigned_user_id { get; set; }
        public int task_status_id { get; set; }
        public Nullable<bool> is_active_bit { get; set; }
        public int order_id { get; set; }
    }
}
