//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ad {
            get {
                return ResourceManager.GetString("ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to create task?  .
        /// </summary>
        internal static string are_you_sure_to_create_task {
            get {
                return ResourceManager.GetString("are_you_sure_to_create_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        internal static string are_you_sure_to_delete {
            get {
                return ResourceManager.GetString("are_you_sure_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned user.
        /// </summary>
        internal static string assigned_user_name {
            get {
                return ResourceManager.GetString("assigned_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string birthdate {
            get {
                return ResourceManager.GetString("birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string birth_date {
            get {
                return ResourceManager.GetString("birth_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string browser {
            get {
                return ResourceManager.GetString("browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked company.
        /// </summary>
        internal static string calistigi_kurum {
            get {
                return ResourceManager.GetString("calistigi_kurum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string enddate {
            get {
                return ResourceManager.GetString("enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string eposta {
            get {
                return ResourceManager.GetString("eposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string eposta_adresi {
            get {
                return ResourceManager.GetString("eposta_adresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated end date.
        /// </summary>
        internal static string estimated_end_date {
            get {
                return ResourceManager.GetString("estimated_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail is exists. Please enter new E-Mail address.
        /// </summary>
        internal static string exists_user_email {
            get {
                return ResourceManager.GetString("exists_user_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string faks1 {
            get {
                return ResourceManager.GetString("faks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string faksi_1 {
            get {
                return ResourceManager.GetString("faksi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter task closing explanation.
        /// </summary>
        internal static string fill_task_closing_explanation {
            get {
                return ResourceManager.GetString("fill_task_closing_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group explanation.
        /// </summary>
        internal static string group_explanation {
            get {
                return ResourceManager.GetString("group_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group manager.
        /// </summary>
        internal static string group_manager {
            get {
                return ResourceManager.GetString("group_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group admin.
        /// </summary>
        internal static string group_manager_name_surname {
            get {
                return ResourceManager.GetString("group_manager_name_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        internal static string group_name {
            get {
                return ResourceManager.GetString("group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone.
        /// </summary>
        internal static string homephone {
            get {
                return ResourceManager.GetString("homephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone.
        /// </summary>
        internal static string home_phone {
            get {
                return ResourceManager.GetString("home_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host .
        /// </summary>
        internal static string host_name {
            get {
                return ResourceManager.GetString("host_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity number.
        /// </summary>
        internal static string identitynumber {
            get {
                return ResourceManager.GetString("identitynumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity number.
        /// </summary>
        internal static string identity_number {
            get {
                return ResourceManager.GetString("identity_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string isactive {
            get {
                return ResourceManager.GetString("isactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company mobile phone.
        /// </summary>
        internal static string isveren_mobile_phone {
            get {
                return ResourceManager.GetString("isveren_mobile_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active/Pasive.
        /// </summary>
        internal static string is_active {
            get {
                return ResourceManager.GetString("is_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company code.
        /// </summary>
        internal static string kurum_kodu {
            get {
                return ResourceManager.GetString("kurum_kodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Please enter e-mail and password.
        /// </summary>
        internal static string login_failed {
            get {
                return ResourceManager.GetString("login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string manager {
            get {
                return ResourceManager.GetString("manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager name.
        /// </summary>
        internal static string manager_name {
            get {
                return ResourceManager.GetString("manager_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square meter.
        /// </summary>
        internal static string metre_kare {
            get {
                return ResourceManager.GetString("metre_kare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone.
        /// </summary>
        internal static string mobilephone {
            get {
                return ResourceManager.GetString("mobilephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone.
        /// </summary>
        internal static string mobile_phone {
            get {
                return ResourceManager.GetString("mobile_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name surname.
        /// </summary>
        internal static string name_surname {
            get {
                return ResourceManager.GetString("name_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        internal static string new_password_not_null {
            get {
                return ResourceManager.GetString("new_password_not_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter repeat-password.
        /// </summary>
        internal static string new_password_repeat_not_null {
            get {
                return ResourceManager.GetString("new_password_repeat_not_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task notification .
        /// </summary>
        internal static string new_task_notification {
            get {
                return ResourceManager.GetString("new_task_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; task at &apos;{1}&apos; asigned to &apos;{2}&apos; . .
        /// </summary>
        internal static string new_task_notification_body {
            get {
                return ResourceManager.GetString("new_task_notification_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter old-password.
        /// </summary>
        internal static string old_password_not_null {
            get {
                return ResourceManager.GetString("old_password_not_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order id.
        /// </summary>
        internal static string order_id {
            get {
                return ResourceManager.GetString("order_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string platform {
            get {
                return ResourceManager.GetString("platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned user.
        /// </summary>
        internal static string project_assigned_name_surname {
            get {
                return ResourceManager.GetString("project_assigned_name_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project description.
        /// </summary>
        internal static string project_description {
            get {
                return ResourceManager.GetString("project_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        internal static string project_name {
            get {
                return ResourceManager.GetString("project_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project owner.
        /// </summary>
        internal static string project_owner {
            get {
                return ResourceManager.GetString("project_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project owner type.
        /// </summary>
        internal static string project_type_name {
            get {
                return ResourceManager.GetString("project_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related group.
        /// </summary>
        internal static string related_group {
            get {
                return ResourceManager.GetString("related_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string related_project_name {
            get {
                return ResourceManager.GetString("related_project_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role changed successfully..
        /// </summary>
        internal static string role_changed_successfully {
            get {
                return ResourceManager.GetString("role_changed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role description.
        /// </summary>
        internal static string role_explanation {
            get {
                return ResourceManager.GetString("role_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role id.
        /// </summary>
        internal static string role_id {
            get {
                return ResourceManager.GetString("role_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string role_name {
            get {
                return ResourceManager.GetString("role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save role information.
        /// </summary>
        internal static string role_related_role_not_defined {
            get {
                return ResourceManager.GetString("role_related_role_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role related user was already defined.
        /// </summary>
        internal static string role_related_users_defined {
            get {
                return ResourceManager.GetString("role_related_users_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string soyad {
            get {
                return ResourceManager.GetString("soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry date.
        /// </summary>
        internal static string startdate {
            get {
                return ResourceManager.GetString("startdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task closing explanation.
        /// </summary>
        internal static string task_closing_explanation {
            get {
                return ResourceManager.GetString("task_closing_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task description.
        /// </summary>
        internal static string task_description {
            get {
                return ResourceManager.GetString("task_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task expired..
        /// </summary>
        internal static string task_expire_end_date_body {
            get {
                return ResourceManager.GetString("task_expire_end_date_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task expired..
        /// </summary>
        internal static string task_expire_end_date_title {
            get {
                return ResourceManager.GetString("task_expire_end_date_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task description.
        /// </summary>
        internal static string task_explanations {
            get {
                return ResourceManager.GetString("task_explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task description added..
        /// </summary>
        internal static string task_explanation_added {
            get {
                return ResourceManager.GetString("task_explanation_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New description &apos;{0}&apos; added on &apos;{1}&apos; .
        /// </summary>
        internal static string task_explanation_added_body {
            get {
                return ResourceManager.GetString("task_explanation_added_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; -&gt; &apos;{1}&apos; on &apos;{2}&apos;..
        /// </summary>
        internal static string task_gonderildi_status_notification_body {
            get {
                return ResourceManager.GetString("task_gonderildi_status_notification_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task history.
        /// </summary>
        internal static string task_history {
            get {
                return ResourceManager.GetString("task_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name.
        /// </summary>
        internal static string task_name {
            get {
                return ResourceManager.GetString("task_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task owner.
        /// </summary>
        internal static string task_owner {
            get {
                return ResourceManager.GetString("task_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task priority.
        /// </summary>
        internal static string task_priority_name {
            get {
                return ResourceManager.GetString("task_priority_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work started.
        /// </summary>
        internal static string task_status_calismaya_baslandi {
            get {
                return ResourceManager.GetString("task_status_calismaya_baslandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task status.
        /// </summary>
        internal static string task_status_name {
            get {
                return ResourceManager.GetString("task_status_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task status changed.
        /// </summary>
        internal static string task_status_notification {
            get {
                return ResourceManager.GetString("task_status_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task denied.
        /// </summary>
        internal static string task_status_reddedildi {
            get {
                return ResourceManager.GetString("task_status_reddedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task completed.
        /// </summary>
        internal static string task_status_tamamlandi {
            get {
                return ResourceManager.GetString("task_status_tamamlandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string telefon1 {
            get {
                return ResourceManager.GetString("telefon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string telefonu_1 {
            get {
                return ResourceManager.GetString("telefonu_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ticari_unvan {
            get {
                return ResourceManager.GetString("ticari_unvan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ticari_unvani {
            get {
                return ResourceManager.GetString("ticari_unvani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction completed successfully.
        /// </summary>
        internal static string transaction_success {
            get {
                return ResourceManager.GetString("transaction_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction completed successfully.Password infos updated.
        /// </summary>
        internal static string transaction_success_with_password {
            get {
                return ResourceManager.GetString("transaction_success_with_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update date.
        /// </summary>
        internal static string update_date {
            get {
                return ResourceManager.GetString("update_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user.
        /// </summary>
        internal static string update_user {
            get {
                return ResourceManager.GetString("update_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Adres.
        /// </summary>
        internal static string user_host_adres {
            get {
                return ResourceManager.GetString("user_host_adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax number.
        /// </summary>
        internal static string vergino {
            get {
                return ResourceManager.GetString("vergino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax admin.
        /// </summary>
        internal static string vergi_dairesi {
            get {
                return ResourceManager.GetString("vergi_dairesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax number.
        /// </summary>
        internal static string vergi_no {
            get {
                return ResourceManager.GetString("vergi_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web page.
        /// </summary>
        internal static string web_sitesi {
            get {
                return ResourceManager.GetString("web_sitesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is diffrent from new password..
        /// </summary>
        internal static string wrong_old_password {
            get {
                return ResourceManager.GetString("wrong_old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is diffrent from repeat password..
        /// </summary>
        internal static string wrong_repeat_password {
            get {
                return ResourceManager.GetString("wrong_repeat_password", resourceCulture);
            }
        }
    }
}
