//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcm.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class gnl_notifications
    {
        public int id { get; set; }
        public System.Guid notification_id { get; set; }
        public Nullable<int> notification_type { get; set; }
        public Nullable<int> notification_module_type { get; set; }
        public Nullable<System.Guid> related_record_id { get; set; }
        public Nullable<System.Guid> notification_user_id { get; set; }
        public string notification_title { get; set; }
        public string notification_body { get; set; }
        public Nullable<System.DateTime> notification_created_date { get; set; }
        public Nullable<bool> notification_shown { get; set; }
        public Nullable<System.DateTime> notification_shown_date { get; set; }
        public Nullable<System.Guid> inserted_by { get; set; }
        public Nullable<System.DateTime> inserted_at { get; set; }
        public Nullable<System.Guid> updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.Guid> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
